# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DataBC
email: data@gov.bc.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qa.data.gov.bc.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude some directories from being included
# Excluding css/ & sass/ because we want control over it
#include: [".htaccess"]
exclude: ['css', '_sass', 'node_modules', 'bower_components', 'bower.json', 'Gruntfile.js', 'package.json']

keep_files: ['_site/css', '_site/js', '_site/fonts']

collections:
  visualizations:
    output: false

# Serving
incremental: true
#detach: true
host: 0.0.0.0
